# Generated by Django 4.2.11 on 2024-04-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("parsed_resume", models.JSONField()),
                ("file", models.FileField(default="", upload_to="")),
                ("uploaded_on", models.DateTimeField(auto_now_add=True)),
                ("parsed", models.BooleanField(default=False)),
                ("resume_insight", models.JSONField(blank=True, default=dict)),
                ("user_id", models.IntegerField(blank=True, default="")),
                ("submitted_form_data", models.JSONField(blank=True, default=dict)),
                (
                    "submitted_pdf_url",
                    models.FileField(blank=True, default="", upload_to=""),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "submitted_pdf_path",
                    models.FileField(blank=True, default="", upload_to=""),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
    ]
