# Generated by Django 5.0.2 on 2024-02-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("address", models.CharField(blank=True, default="", max_length=100)),
                ("firstname", models.CharField(blank=True, default="", max_length=100)),
                ("lastname", models.CharField(blank=True, default="", max_length=100)),
                ("education", models.TextField(default="")),
                ("work_experience", models.TextField(default="")),
            ],
            options={
                "ordering": ["created"],
            },
        ),
    ]
