# Generated by Django 4.2.10 on 2024-02-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copilot_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="parsed_resume",
            field=models.TextField(default=""),
        ),
    ]
