# Generated by Django 4.2.10 on 2024-02-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copilot_api", "0002_resume_parsed_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="parsed_resume",
            field=models.JSONField(),
        ),
    ]
