# Generated by Django 4.2.10 on 2024-02-21 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("copilot_api", "0003_alter_resume_parsed_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="file",
            field=models.FileField(default="", upload_to=""),
        ),
        migrations.AddField(
            model_name="resume",
            name="uploaded_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
