# Generated by Django 4.2.10 on 2024-02-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copilot_api", "0004_resume_file_resume_uploaded_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="parsed",
            field=models.BooleanField(default=False),
        ),
    ]
