# Generated by Django 4.2.10 on 2024-02-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copilot_api", "0005_resume_parsed"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="resume_insight",
            field=models.JSONField(default=None),
        ),
    ]
