# Generated by Django 4.2.10 on 2024-02-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copilot_api", "0008_alter_resume_resume_insight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="resume_insight",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
